###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 64             # Batch size.
pin_memory: true           # Whether to pin memory in Pytorch DataLoader.
num_workers: 4             # Number of workers in Pytorch DataLoader.
allow_cache: true          # Whether to allow cache in dataset. If true, it requires cpu memory.

###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 100000                # Number of training steps.
save_interval_steps: 1000              # Interval steps to save checkpoint.
eval_interval_steps: 1000               # Interval steps to evaluate the network.
log_interval_steps: 1000               # Interval steps to record the training log.
